### ISSUE TITLE
[S1-PBI4] Perpanjangan SIM

### ISSUE THREAD

**Issue by Annisa190516** [SI-RPL-2021/SI4203-ESS#10]
Sebagai User Ingin melakukan perpanjangan SIM online sehingga tidak perlu datang ke tempat secara langsung
https://www.figma.com/file/G9yNtSJN7LvjfggH1cUylL/E-SS-Mockup?node-id=0%3A1

**Comment by nevada002** [comment]
Sebagai User Ingin melakukan perpanjangan SIM online sehingga tidak perlu datang ke tempat secara langsung
[https://www.figma.com/file/G9yNtSJN7LvjfggH1cUylL/E-SS-Mockup?node-id=0%3A1](url)
