### ISSUE TITLE
[S1-PBI10] Login

### ISSUE THREAD

**Issue by nevada002** [SI-RPL-2021/SI4203-ESS#12]
Saya sebagai User ingin melakukan login sehingga saya dapat menggunakan fitur yang tersedia

**Comment by naufalhanifr** [comment]
Saya sebagai User ingin melakukan login sehingga saya dapat menggunakan fitur yang tersedia
[https://www.figma.com/proto/G9yNtSJN7LvjfggH1cUylL/E-SS-Mockup?node-id=30%3A4&scaling=min-zoom](https://www.figma.com/proto/G9yNtSJN7LvjfggH1cUylL/E-SS-Mockup?node-id=30%3A4&scaling=min-zoom)
