### ISSUE TITLE
[S1-PBI7] Laporan Kehilangan SIM

### ISSUE THREAD

**Issue by nevada002** [SI-RPL-2021/SI4203-ESS#9]
Saya sebagai User ingin mengurus SIM yang hilang sehingga mendapatkan SIM baru

**Comment by naufalhanifr** [comment]
Saya sebagai User ingin mengurus SIM yang hilang sehingga mendapatkan SIM baru
[https://www.figma.com/proto/G9yNtSJN7LvjfggH1cUylL/E-SS-Mockup?node-id=4%3A2&scaling=min-zoom](https://www.figma.com/proto/G9yNtSJN7LvjfggH1cUylL/E-SS-Mockup?node-id=4%3A2&scaling=min-zoom)
